# site settings
title: Forty
subtitle: by HTML5 UP
email: mathieu.vieillefont@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/Portfolio_jekyll_github.io/" # the subpath of your site, e.g. /blog
url: "https://mamath79.github.io/" # the base hostname & protocol for your site
author:
street_address: 
city: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Mamath79
  LinkedIn: https://www.linkedin.com/in/mathieu-vieillefont/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
